name: Build python-bookworm

on:
  workflow_dispatch:
  schedule:
    # New image every Monday
    - cron: "0 4 * * 1"

jobs:
  bookworm:
    name: python-bookworm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone docker-library/python
        with:
          repository: docker-library/python
          fetch-depth: '1'
          path: 'docker-python'

      - name: Generate Dockerfile
        run: |
          cp -v "$(find python -maxdepth 1 -type d -regex '^python/3\.[0-9]+' | sort -V --reverse | head -n 1)/slim-bullseye/Dockerfile" Dockerfile
          sed -i 's/FROM debian:bullseye-slim/FROM debian:bookworm-slim/g' Dockerfile

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ghcr.io/intfish/python-bookworm:latest
